app = "git-orik-in"
primary_region = "ord"

[[vm]]
size = "shared-cpu-2x"
memory = "2gb"

[build]
image = "gitea/gitea:1.24.3"

[deploy]
strategy = "immediate"

[http_service]
internal_port = 3000
force_https = true
auto_stop_machines = false
auto_start_machines = true
min_machines_running = 1

[[http_service.checks]]
grace_period = "10s"
interval = "60s"
method = "GET"
timeout = "10s"
path = "/"

[[services]]
internal_port = 2222
protocol = "tcp"

[[services.ports]]
port = 22

[mounts]
source = "git_orik_in_data"
destination = "/data"
initial_size = "20gb"
